# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46214c00ac1e95764b2a714d2cd605b279819bc8c6c8837359d9e4ce0f587a96ce2d6d193976ec12101e3f136a7c507ef27c10919d4bf233b936d6be937d0d8a

test:
  secret_key_base: 3eeb54571e5317fcd82b2870e94d157e7960dce0dc733c6c980bd0d8e76a2765ce6c67feed7b8b01478ab4c940eed93e0ddf8e16da845620d538699489555127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
